http:
  middlewares:    
    default-security-headers:
      headers:
        browserXssFilter: true                            # X-XSS-Protection=1; mode=block
        contentTypeNosniff: true                          # X-Content-Type-Options=nosniff
        forceSTSHeader: true                              # Add the Strict-Transport-Security header even when the connection is HTTP
        frameDeny: false                                   # X-Frame-Options=deny
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true                        # Add includeSubdomains to the Strict-Transport-Security header
        stsPreload: true                                  # Add preload flag appended to the Strict-Transport-Security header
        stsSeconds: 3153600                              # Set the max-age of the Strict-Transport-Security header (63072000 = 2 years)
        contentSecurityPolicy: "default-src 'self'"     
        customRequestHeaders:
          X-Forwarded-Proto: https
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    unraid:
      entryPoints:
        - "https"
      rule: "Host(`unraid.darksaber.fyi`)"
      middlewares:
        - default-security-headers
        - https-redirectscheme
      tls: {}
      service: unraid
    dns-01:
      entryPoints:
        - "https"
      rule: "Host(`dns-01.darksaber.fyi`)"
      middlewares:
        - default-security-headers
        - https-redirectscheme
      tls: {}
      service: dns-01

  services:
    unraid:
      loadBalancer:
        servers:
          - url: "http://10.0.100.2"
        passHostHeader: true
    dns-01:
      loadBalancer:
        servers:
          - url: "http://10.0.100.253:5380"
        passHostHeader: true