---
- name: Install Podman
  hosts: all
  become: true
  tasks:
    - name: Install Podman
      apt:
        name: podman
        state: present
        update_cache: yes

    - name: Verify Podman installation
      command: podman --version
      register: podman_version
      changed_when: false

    - name: Display Podman version
      debug:
        msg: "Installed Podman version: {{ podman_version.stdout }}"