---
services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    networks:
      - proxy
      - backend
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm
      - DB_USER=romm-user
      - DB_PASSWD=${DB_PASSWORD}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
    volumes:
      - romm_resources:/romm/resources
      - romm_redis_data:/redis-data
      - /mnt/data/romm/library:/romm/library
      - /mnt/data/romm/assets:/romm/assets
      - /mnt/data/romm/config:/romm/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.romm.rule=Host(`games.darksaber.fyi`)"
      - "traefik.http.routers.romm.entrypoints=https"
      - "traefik.http.routers.romm.tls=true"
      - "traefik.http.routers.romm.middlewares=default-whitelist@file"
      - "traefik.http.services.romm.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true
    restart: unless-stopped

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    networks:
      - backend
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  proxy:
    external: true
  backend:
    internal: true

volumes:
  mysql_data:
  romm_resources:
  romm_redis_data: