---
services:
  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    container_name: plexautolanguages
    environment:
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TZ=Europe/Berlin
    volumes:
      - /home/mgrsys/docker/plex-auto-languages/config:/config
    restart: unless-stopped