---
- name: Install Podman
  hosts: all
  become: true
  vars:
    podman_user: "{{ ansible_user }}"
    podman_group: "{{ ansible_user }}"
    stacks_path: /opt/stacks

  tasks:
    - name: Install Podman
      apt:
        name: podman
        state: present
        update_cache: yes

    - name: Configure unprivileged port start
      lineinfile:
        path: /etc/sysctl.d/user_priv_ports.conf
        line: "net.ipv4.ip_unprivileged_port_start=80"
        create: yes

    - name: Apply sysctl settings
      command: sysctl --system
      changed_when: false

    - name: Create stacks directory with proper permissions
      file:
        path: "{{ stacks_path }}"
        state: directory
        owner: "{{ podman_user }}"
        group: "{{ podman_group }}"
        mode: '0755'
        recurse: yes

    - name: Verify Podman installation
      command: podman --version
      register: podman_version
      changed_when: false

    - name: Display Podman version
      debug:
        msg: "Installed Podman version: {{ podman_version.stdout }}"