---
- name: Install Podman
  hosts: all
  become: true
  vars:
    podman_user: "{{ ansible_user }}"
    podman_group: "{{ ansible_user }}"
    stacks_path: /opt/stacks

  tasks:
    - name: Install Podman
      apt:
        name: podman
        state: present
        update_cache: yes

    - name: Create stacks directory with proper permissions
      file:
        path: "{{ stacks_path }}"
        state: directory
        owner: "{{ podman_user }}"
        group: "{{ podman_group }}"
        mode: '0755'
        recurse: yes

    - name: Create proxy network
      containers.podman.podman_network:
        name: proxy
        state: present

    - name: Verify Podman installation
      command: podman --version
      register: podman_version
      changed_when: false

    - name: Display Podman version
      debug:
        msg: "Installed Podman version: {{ podman_version.stdout }}"