http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    gzip:
      compress: {}

    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"
  
    pocket-id:
      plugin:
        traefik-oidc-auth:
          Secret: "{{ env `POCKET_ID_SECRET` }}"
          CallbackUri: "https://auth.darksaber.fyi/oidc/callback"
          SessionCookie:
            Domain: ".darksaber.fyi"
          Provider:
            Url: "https://id.darksaber.fyi"
            ClientId: 4a6cbb74-10e6-4644-a3f6-92e23c67c56a
            ClientSecret: "{{ env `POCKET_ID_CLIENT_SECRET` }}"
            UsePkce: false
          Scopes: ["openid", "profile", "email"]

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
        - gzip