http:
  routers:
    pve-s13-01:
      entryPoints:
        - "https"
      rule: "Host(`pve-s13-01.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: pve-s13-01
    pbs:
      entryPoints:
        - "https"
      rule: "Host(`pbs.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: pbs
    unraid:
      entryPoints:
        - "https"
      rule: "Host(`unraid.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: unraid
    sab:
      entryPoints:
        - "https"
      rule: "Host(`sab.darksaber.fyi`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - gzip
        - default-whitelist
      tls:
        options: default
      service: sab


  services:
    pve-s13-01:
      loadBalancer:
        servers:
          - url: "https://pve-s13-01.local.darksaber.fyi:8006"
        passHostHeader: true
    pbs:
      loadBalancer:
        servers:
          - url: "https://pbs-unraid.local.darksaber.fyi:8007/"
        passHostHeader: true
    unraid:
      loadBalancer:
        servers:
          - url: "http://unraid.local.darksaber.fyi"
        passHostHeader: true
    sab:
      loadBalancer:
        servers:
          - url: "http://srv-docker.local.darksaber.fyi:8080"
        passHostHeader: true