services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=${SERVER_CITIES}
    ports:
      - 8080:8080 #Sab
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/mgrsys/docker/arr-stack/sabnzbd/config:/config
      - /home/mgrsys/docker/arr-stack/sabnzbd/backup:/backup
      - /home/mgrsys/docker/arr-stack/sabnzbd/logs:/logs
      - /mnt/data/usenet/complete:/data/usenet/complete
      - /mnt/data/usenet/incomplete:/data/usenet/incomplete
    network_mode: "service:gluetun"
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - /home/mgrsys/docker/arr-stack/prowlarr/config:/config
    ports:
      - 9696:9696
    networks:
      - proxy
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
      traefik.http.routers.prowlarr.entrypoints: https
      traefik.http.routers.prowlarr.rule: "Host(`prowlarr.darksaber.fyi`)"
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.routers.prowlarr.tls: "True"
    restart: unless-stopped

  umlautadaptarr:
    image: pcjones/umlautadaptarr:latest
    container_name: umlautadaptarr
    environment:
      - TZ=Europe/Berlin
      - SONARR__ENABLED_true
      - SONARR__HOST=http://sonarr:8989
      - SONARR__APIKEY=${SONARR_APIKEY}

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - /home/mgrsys/docker/arr-stack/sonarr/config:/config
      - /mnt/data:/data
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
      traefik.http.routers.prowlarr.entrypoints: https
      traefik.http.routers.prowlarr.rule: "Host(`prowlarr.darksaber.fyi`)"
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.routers.prowlarr.tls: "True"
    restart: unless-stopped

networks:
  proxy:
    external: true

  