services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - proxy
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=${SERVER_CITIES}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sab.service=sab"
      - "traefik.http.routers.sab.rule=Host(`sab.darksaber.fyi`)"
      - "traefik.http.routers.sab.entrypoints=https"
      - "traefik.http.routers.sab.tls=true"
      - "traefik.http.services.sab.loadbalancer.server.port=8181"
      - "traefik.http.routers.sab.middlewares=default-whitelist@file"
      - "traefik.http.routers.searxng.service=searxng"
      - "traefik.http.routers.searxng.rule=Host(`search.darksaber.fyi`)"
      - "traefik.http.routers.searxng.entrypoints=https"
      - "traefik.http.routers.searxng.tls=true"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
      - "traefik.http.routers.searxng.middlewares=default-whitelist@file"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/mgrsys/docker/arr-stack/sabnzbd/config:/config
      - /home/mgrsys/docker/arr-stack/sabnzbd/backup:/backup
      - /home/mgrsys/docker/arr-stack/sabnzbd/logs:/logs
      - /mnt/data/usenet/complete:/data/usenet/complete
      - /mnt/data/usenet/incomplete:/data/usenet/incomplete
    network_mode: "service:gluetun"
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - /home/mgrsys/docker/arr-stack/prowlarr/config:/config
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.darksaber.fyi`)"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.prowlarr.middlewares=default-whitelist@file"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

  umlautadaptarr:
    image: pcjones/umlautadaptarr:latest
    container_name: umlautadaptarr
    environment:
      - TZ=Europe/Berlin
      - SONARR__ENABLED=true
      - SONARR__HOST=http://sonarr:8989
      - SONARR__APIKEY=${SONARR_APIKEY}
    networks:
      - proxy
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - /home/mgrsys/docker/arr-stack/sonarr/config:/config
      - /mnt/data:/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.darksaber.fyi`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.middlewares=default-whitelist@file"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - /home/mgrsys/docker/arr-stack/radarr/config:/config
      - /mnt/data:/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.darksaber.fyi`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.middlewares=default-whitelist@file"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}        
    volumes:
        - /home/mgrsys/docker/arr-stack/searxng/config:/etc/searxng:rw
    # cap_drop:
    #   - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  proxy:
    external: true

  