---
- name: Update Debian LXC Containers and Technitium DNS
  hosts: dns
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Update system packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Ensure curl is installed
      apt:
        name: curl
        state: present

    - name: Update Technitium DNS
      shell: curl -sSL https://download.technitium.com/dns/install.sh | sudo bash
      args:
        executable: /bin/bash