---
- name: Deploy Wiki.js with PostgreSQL
  hosts: all
  become: false
  vars:
    wiki_data_path: /opt/stacks/wikijs
    wiki_version: "2"
    postgres_version: "15-alpine"

  pre_tasks:
    - name: Get secrets from 1Password
      shell: |
        OP_SERVICE_ACCOUNT_TOKEN="{{ op_token }}" op read "op://secrets/WikiJS/Env/Username"
      register: db_username_output
      no_log: true

    - name: Get DB password
      shell: |
        OP_SERVICE_ACCOUNT_TOKEN="{{ op_token }}" op read "op://secrets/WikiJS/Env/Password"
      register: db_password_output
      no_log: true

    - name: Get DB name
      shell: |
        OP_SERVICE_ACCOUNT_TOKEN="{{ op_token }}" op read "op://secrets/WikiJS/Env/Database"
      register: db_name_output
      no_log: true

    - name: Set fact for secrets
      set_fact:
        db_username: "{{ db_username_output.stdout }}"
        db_password: "{{ db_password_output.stdout }}"
        db_name: "{{ db_name_output.stdout }}"
      no_log: true

  tasks:
    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ wiki_data_path }}"
        - "{{ wiki_data_path }}/db"

    - name: Create proxy network if not present
      containers.podman.podman_network:
        name: proxy
        state: present

    - name: Create internal backend network if not present
      containers.podman.podman_network:
        name: backend
        state: present
        internal: true

    - name: Create PostgreSQL container
      containers.podman.podman_container:
        name: wiki-db
        image: "docker.io/library/postgres:{{ postgres_version }}"
        state: started
        restart_policy: always
        env:
          POSTGRES_USER: "{{ db_username }}"
          POSTGRES_PASSWORD: "{{ db_password }}"
          POSTGRES_DB: "{{ db_name }}"
        volumes:
          - "{{ wiki_data_path }}/db:/var/lib/postgresql/data:Z"
        network: backend

    - name: Create Wiki.js container
      containers.podman.podman_container:
        name: wiki
        image: "ghcr.io/requarks/wiki:{{ wiki_version }}"
        state: started
        restart_policy: always
        env:
          DB_TYPE: postgres
          DB_HOST: wiki-db
          DB_PORT: 5432
          DB_USER: "{{ db_username }}"
          DB_PASS: "{{ db_password }}"
          DB_NAME: "{{ db_name }}"
        ports:
          - "3000:3000"
        network: "backend,proxy"