---
services:
  redlib:
    image: quay.io/redlib/redlib:latest
    container_name: redlib
    networks:
      - proxy
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redlib.rule=Host(`reddit.darksaber.fyi`)"
      - "traefik.http.routers.redlib.entrypoints=https"
      - "traefik.http.routers.redlib.tls=true"
      - "traefik.http.services.redlib.loadbalancer.server.port=8080"
      - "traefik.http.routers.redlib.middlewares=default-whitelist@file"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true