---
- name: Post-provisioning setup for VM
  hosts: docker
  become: true

  tasks:
    - name: Ensure system packages are up to date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Allow mgrsys to run sudo without password
      copy:
        dest: /etc/sudoers.d/mgrsys
        content: "mgrsys ALL=(ALL) NOPASSWD:ALL"
        mode: 0440

    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

    - name: Install 1Password CLI
      shell: |
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
        echo 'deb [signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | tee /etc/apt/sources.list.d/1password.list
        apt update && apt install -y 1password-cli

    - name: Install Docker
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Add mgrsys to Docker group
      user:
        name: mgrsys
        groups: docker
        append: yes

    - name: Ensure NFS utilities are installed
      apt:
        name: nfs-common
        state: present

    - name: Create mount point for NFS share
      file:
        path: /mnt/data
        state: directory
        mode: '0755'

    - name: Mount external NFS share
      mount:
        path: /mnt/data
        src: unraid.local.darksaber.fyi:/mnt/user/data
        fstype: nfs
        opts: rw,noatime,_netdev,vers=4
        state: mounted

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
