---
- name: Ensure sabnzbd host_whitelist contains required domains
  hosts: docker
  become: true
  tasks:
    - name: Update host_whitelist
      ansible.builtin.replace:
        path: /home/mgrsys/docker/gluetun-stack/sabnzbd/config/sabnzbd.ini
        regexp: '^(host_whitelist\s*=\s*[^,\n]*)(,)?(.*)$'
        replace: '\1,srv-docker.local.darksaber.fyi,sabnzbd,sab.darksaber.fyi\3'
      register: config_update

    - name: Replace port number
      replace:
        path: /home/mgrsys/docker/gluetun-stack/sabnzbd/config/sabnzbd.ini
        regexp: 'port = 8080'
        replace: 'port = 8181'
      register: config_update

    - name: Restart sabnzbd container
      community.docker.docker_container:
        name: sabnzbd
        restart: true
      when: config_update.changed