---
- name: Docker Gluetun stack
  hosts: docker
  vars:
    service_name: gluetun-stack
    base_dir: "/home/mgrsys/docker/{{ service_name }}"
    compose_dir: "{{ base_dir }}/compose"
    sabnzbd_dir: "{{ base_dir }}/sabnzbd"
    sabnzbd_bu_dir: "{{ sabnzbd_dir }}/backup"
    sabnzbd_logs_dir: "{{ sabnzbd_dir }}/logs"
    searxng_dir: "{{ base_dir }}/searxng"
    repo_dir: "/home/mgrsys/tmp"
    github_repo: "https://github.com/L3odalton/homelab.git"
    docker_network: proxy

  tasks:
    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ compose_dir }}"
        - "{{ sabnzbd_dir }}"
        - "{{ sabnzbd_bu_dir }}"
        - "{{ sabnzbd_logs_dir }}"
        - "{{ searxng_dir }}"

    - name: Ensure docker network(s) exist
      docker_network:
        name: "{{ docker_network }}"
        state: present

    - name: Clone/pull latest configuration from GitHub
      git:
        repo: "{{ github_repo }}"
        dest: "{{ repo_dir }}"
        update: yes
        force: yes
      register: git_status

    - name: Copy files using a loop
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
      loop:
        - { src: "{{ repo_dir }}/ansible/docker/{{ service_name }}/compose/", dest: "{{ compose_dir }}/" }
        - { src: "{{ repo_dir }}/ansible/docker/{{ service_name }}/searxng/", dest: "{{ searxng_dir }}/" }

    - name: Remove existing .env files
      file:
        path: "{{ compose_dir }}/{{ item }}"
        state: absent
      loop:
        - ".env"
      ignore_errors: yes

    - name: Remove existing settings.yml files
      file:
        path: "{{ searxng_dir }}/{{ item }}"
        state: absent
      loop:
        - "settings.yml"
      ignore_errors: yes

    - name: Inject Secrets from 1Password
      shell: |
        op inject -i "{{ item.input }}" -o "{{ item.output }}"
        test -f "{{ item.output }}"
      loop:
        - { input: "{{ compose_dir }}/.env.tpl", output: "{{ compose_dir }}/.env", name: ".env" }
        - { input: "{{ searxng_dir }}/settings.yml.tpl", output: "{{ searxng_dir }}/settings.yml", name: "settings.yml" }
      environment:
        OP_SERVICE_ACCOUNT_TOKEN: "{{ op_token }}"
      no_log: yes

    - name: Deploy/update and restart docker container
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        files:
          - docker-compose.yml
        state: present
        pull: policy
        recreate: always

    - name: Remove Git Tmp Folder
      file:
        path: "{{ repo_dir }}"
        state: absent