---
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - proxy
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=${SERVER_CITIES}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sab.service=sab"
      - "traefik.http.routers.sab.rule=Host(`sab.darksaber.fyi`)"
      - "traefik.http.routers.sab.entrypoints=https"
      - "traefik.http.routers.sab.tls=true"
      - "traefik.http.services.sab.loadbalancer.server.port=8181"
      - "traefik.http.routers.sab.middlewares=default-whitelist@file"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/mgrsys/docker/gluetun-stack/sabnzbd/config:/config
      - /home/mgrsys/docker/gluetun-stack/sabnzbd/backup:/backup
      - /home/mgrsys/docker/gluetun-stack/sabnzbd/logs:/logs
      - /mnt/data/usenet/complete:/data/usenet/complete
      - /mnt/data/usenet/incomplete:/data/usenet/incomplete
    network_mode: "service:gluetun"
    restart: unless-stopped

networks:
  proxy:
    external: true