---
- name: Initial Ubuntu Server Setup
  hosts: all
  become: true
  tasks:
    - name: Allow mgrsys to run sudo commands without password
      lineinfile:
        path: /etc/sudoers.d/mgrsys
        line: "mgrsys ALL=(ALL) NOPASSWD:ALL"
        create: yes
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Install QEMU Guest Agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes

    - name: Enable and start QEMU Guest Agent service
      service:
        name: qemu-guest-agent
        state: started
        enabled: yes

    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        validate: '/usr/sbin/sshd -t -f %s'

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Perform full system upgrade
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes
      register: upgrade_output

    - name: Reboot if required
      reboot:
      when: upgrade_output.changed