---
services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    container_name: pocket-id
    networks:
      - proxy
    env_file: .env
    volumes:
      - /home/mgrsys/docker/pocket-id/data:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pocket-id.rule=Host(`id.darksaber.fyi`)"
      - "traefik.http.routers.pocket-id.entrypoints=https"
      - "traefik.http.routers.pocket-id.tls=true"
      - "traefik.http.services.pocket-id.loadbalancer.server.port=80"
      - "traefik.http.routers.pocket-id.middlewares=default-whitelist@file"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true