---
- name: Deploy Portainer with Podman
  hosts: all
  become: false
  vars:
    portainer_version: "2.21.5"

  tasks:
    - name: Create Portainer directory
      file:
        path: /opt/stacks/portainer
        state: directory
        mode: '0755'

    - name: Create Portainer container
      containers.podman.podman_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce:{{ portainer_version }}"
        state: started
        restart_policy: always
        privileged: true
        ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - /opt/stacks/portainer:/data
          - /run/podman/podman.sock:/var/run/docker.sock:Z
        network: proxy
        force_restart: true