---
- name: Plex-Auto-Languages Docker container
  hosts: docker
  vars:
    service_name: plex-auto-languages
    base_dir: "/home/mgrsys/docker/{{ service_name }}"
    compose_dir: "{{ base_dir }}/compose"
    repo_dir: "/home/mgrsys/tmp"
    github_repo: "https://github.com/L3odalton/homelab.git"

  tasks:
    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ compose_dir }}"

    - name: Clone/pull latest configuration from GitHub
      git:
        repo: "{{ github_repo }}"
        dest: "{{ repo_dir }}"
        update: yes
        force: yes
      register: git_status

    - name: Copy files using a loop
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
      loop:
        - { src: "{{ repo_dir }}/ansible/docker/{{ service_name }}/compose/", dest: "{{ compose_dir }}/" }

    - name: Deploy/update and restart docker container
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        files:
          - docker-compose.yml
        state: present
        pull: policy
        recreate: always

    - name: Remove Git Tmp Folder
      file:
        path: "{{ repo_dir }}"
        state: absent