---
- name: Deploy and update Traefik
  hosts: docker
  vars:
    service_name: traefik
    base_dir: "/home/mgrsys/docker"
    compose_dir: "{{ base_dir }}/{{ service_name }}"
    config_dir: "{{ compose_dir }}/config"
    repo_dir: "{{ base_dir }}/repo"
    github_repo: "https://github.com/L3odalton/homelab.git"

  tasks:
    - name: Ensure service and config directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ compose_dir }}"
        - "{{ config_dir }}"

    - name: Clone/pull latest configuration from GitHub
      git:
        repo: "{{ github_repo }}"
        dest: "{{ repo_dir }}"
        update: yes
        force: yes
      register: git_status

    - name: Ensure docker network exists
      docker_network:
        name: "proxy"
        state: present

    - block:
        - name: Copy docker-compose files
          copy:
            src: "{{ repo_dir }}/ansible/docker/{{ service_name }}/compose/"
            dest: "{{ compose_dir }}/"
            remote_src: yes
          register: compose_config

        - name: Check if .env needs to be updated
          stat:
            path: "{{ compose_dir }}/.env"
          register: env_file

        - name: Check if .env.tpl has been modified
          stat:
            path: "{{ compose_dir }}/.env.tpl"
          register: env_tpl_file

        - name: Inject .env file using 1password
          shell: |
            op inject -i {{ compose_dir }}/.env.tpl -o {{ compose_dir }}/.env
            test -f {{ compose_dir }}/.env
          environment:
            OP_SERVICE_ACCOUNT_TOKEN: "{{ op_token }}"
          register: env_config
          no_log: yes
          when: not env_file.stat.exists or env_tpl_file.stat.mtime > env_file.stat.mtime

        - name: Check if cf-token needs to be updated
          stat:
            path: "{{ compose_dir }}/cf-token"
          register: cf_token_file

        - name: Check if cf-token.tpl has been modified
          stat:
            path: "{{ compose_dir }}/cf-token.tpl"
          register: cf_token_tpl_file

        - name: Inject .cf-token file using 1password
          shell: |
            op inject -i {{ compose_dir }}/cf-token.tpl -o {{ compose_dir }}/cf-token
            test -f {{ compose_dir }}/cf-token
          environment:
            OP_SERVICE_ACCOUNT_TOKEN: "{{ op_token }}"
          register: cf_token_config
          no_log: yes
          when: not cf_token_file.stat.exists or cf_token_tpl_file.stat.mtime > cf_token_file.stat.mtime

        - name: Copy configuration files
          copy:
            src: "{{ repo_dir }}/ansible/docker/{{ service_name }}/config/"
            dest: "{{ config_dir }}/"
            remote_src: yes
          register: config_files

        - name: Create acme.json with correct permission if it does not exist
          ansible.builtin.file:
            path: "{{ config_dir }}/acme.json"
            state: touch
            mode: "0600"
            owner: "mgrsys"
            group: "mgrsys"

      when: git_status.changed

    - name: Deploy/update and restart container if configs changed
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        files:
          - docker-compose.yml
        state: present
        pull: always
        recreate: always
      when: >
        git_status.changed or
        compose_config.changed or
        env_config.changed or
        cf_token_config.changed or
        config_files.changed